---

# The Playbook of dm

- name: check config locally
  hosts: localhost
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_static

- name: deploying dm-worker
  hosts: dm_worker_servers
  tags:
    - dm-worker
  roles:
    - dm-worker

- name: deploying dm-master
  hosts: dm_master_servers
  tags:
    - dm-master
  roles:
    - dm-master
