---

# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
binary_dir:    "{{ playbook_dir }}/resources/bin"
